resources:
  io_manager_ds:
    config:
      base_path: /app/ftzard/data
      file_name: tokenized_data.joblib
  io_manager_sd:
    config:
      base_path: /app/ftzard/data
      file_name: retraining_data.joblib
  output_notebook_io_manager:
    config:
      asset_key_prefix: []
