MLFLOW:
  TRACKING:
    URI: "sqlite:////app/ftzard/pipeline/notebooks/mlflow.db"
  EXPERIMENT:
    NAME: senetiment_analysis
  MODEL:
    NAME: FalconSentiAnalysis

HUGGINGFACE:
  MODEL:
    NAME: tiiuae/falcon-7b